# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: 羊肉泡馍与糖蒜
email: crownpku@gmail.com
description: Solve some problems and make life easier.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://crownpku.com" # the base hostname & protocol for your site
github_username: crownpku

# Build settings
markdown: kramdown

#Additional by crownpku
# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics: UA-82231722-1
gems:
  - jekyll-seo-tag